name: 'Setup Environment'
description: 'Install uv, Python, and project dependencies'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.12'
  uv-version:
    description: 'uv version to install'
    required: false
    default: 'latest'
  extras:
    description: 'Extra dependencies to install (e.g., test, dev)'
    required: false
    default: 'test'

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: ${{ inputs.uv-version }}

    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: uv sync --extra ${{ inputs.extras }}
